name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Call the 'python-publish.yml' workflow
      - name: Run Python Publish Workflow
        uses: ./.github/workflows/python-publish.yml
