name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  deploy:
    uses: ./.github/workflows/python-publish.yml
    with:
      user: ashishgargmp
      password: ${{ secrets.PYPI_API_TOKEN }}
